services:
  - type: web
    name: dashboard-recommendation
    runtime: python
    rootDir: 04_Dashboard_Recommendation
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn dashboard.app:server
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.7
